name: afrik_flow
description: "AfrikFlow est une application web et mobile révolutionnaire conçue pour faciliter les transactions financières en Afrique de l'Ouest."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.4.1
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  carousel_slider: ^5.0.0
  phosphor_flutter: ^2.1.0
  pin_code_fields: ^8.0.1
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  slide_action: ^0.0.2
  flutter_local_notifications: ^17.2.3
  flutter_slidable: ^3.1.1
  image_picker: ^1.1.2
  image: ^4.2.0
  url_launcher: ^6.3.1
  share_plus: ^10.0.3
  lottie: ^3.1.3
  cached_network_image: ^3.4.1
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.7.0
  webview_flutter_wkwebview: ^3.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/splash/
    - assets/onboard/
    - assets/logos/
    - assets/animations/

flutter_native_splash:
  color: "#eeeeee"
  image: "assets/images/1.png"
  android_12:
    image: "assets/images/1.png"

flutter_launcher_icons:
  android: true
  image_path: "assets/images/symbol-afrikflow.png"
  adaptive_icon_background: "assets/images/symbol-afrikflow.png"
  adaptive_icon_foreground: "assets/images/symbol-afrikflow.png"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
